language: r
cache: packages

addons:
  apt:
    packages:
      - libapparmor-dev
      - libprotobuf-dev
      - protobuf-compiler
      - libicu-dev

branches:
  only:
  - master

env:
  global:
    - secure: "IQfI++lRrhKcnlPqbIonEGWtgJdVwISbgLlZzwRyfoujg3LUNA8BH7D3mKZdcHsfDAqLTzQzhLqracTh5ZTqPs4Jm8IrY35Dhj9mR24yE2lQIXIhcLBuG62SyK21TXUT0W85BEUJOxtr4GXaEj0jlBxGCbOVjvpIz48ZyEPw4PXIFmjeVns0tEfEkYjhck2UZPrDLG6PaxxP+dfVYa+WkxFB4nZcvN/cbVO5PU15d3dvgdtq9T6uoyPT418eH4R0LBFjn6oZ5gTYvpKqrZdT2ZPwnN4/dCR6bK+4qHwob75ctPdfu6judq7le4gOpfJACAz3SUu1mMZCtDHblk+R+OM4b8SuOVX8ICep6Rzot0UOpWMn94II5e5A7X6O0GsMxHqFT4PCsBMfIX+mLpdF4VR7C7LgQ/hi7d15rll+qCRwVnhxwqrhIH9/jKRMDI0cakht3/OlaGWiGtg3nZ78PmZViU1nSu1fxVuJYgd4Uc74PdhXigB+pEtbUOqiR3AAyB314zE2bBk4WrTF+Gs6MiCreebtFJymbfX97sPbShRYTsrA7MNNQsG4JU8pYpzIb5D2KR3KM5d8QAQAVIBKIR76lKXJvYixUXF0QsygmcZ8SLf2eO1Fy4m/LuGlET8MMZYEWfsBLMFR+8plQo24sp52/O010CDd10+XRk3tXY4="

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh
